-- VitalPower Relay schema (Docs/architecture.md §3), Postgres. Shared file: change only at a sync point.
-- Idempotent: server/db.ts runs it on every start. Timestamps stay ISO-8601 text (UTC, milliseconds, Z), as the API returns them.

CREATE OR REPLACE FUNCTION iso(t timestamptz) RETURNS text LANGUAGE sql STABLE
  AS $$ SELECT to_char(t AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

-- After rows are inserted with explicit ids (seed, migration), the next generated id must come after them.
CREATE OR REPLACE FUNCTION sync_ids() RETURNS void LANGUAGE plpgsql AS $$
DECLARE t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.columns
    WHERE table_schema = current_schema() AND column_name = 'id' AND is_identity = 'YES' LOOP
    EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, ''id''), COALESCE((SELECT max(id) FROM %I), 0) + 1, false)', t, t);
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS organizations (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  kind          TEXT NOT NULL CHECK (kind IN ('responder','facility')),
  org_type      TEXT NOT NULL CHECK (org_type IN ('health-plan','municipality','clinic','supplier','care-home','other')),
  contact_email TEXT,
  message       TEXT,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at    TEXT NOT NULL DEFAULT iso(now()),
  reviewed_by   INTEGER, -- REFERENCES users(id), added below: users does not exist yet
  reviewed_at   TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL,
  role   TEXT NOT NULL CHECK (role IN ('caregiver','coordinator','admin')),
  org_id INTEGER REFERENCES organizations(id)
);

DO $$ BEGIN
  ALTER TABLE organizations ADD CONSTRAINT organizations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS org_municipalities (
  org_id       INTEGER NOT NULL REFERENCES organizations(id),
  municipality TEXT NOT NULL,
  PRIMARY KEY (org_id, municipality)
);

CREATE TABLE IF NOT EXISTS patients (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caregiver_id    INTEGER NOT NULL REFERENCES users(id),
  facility_id     INTEGER REFERENCES organizations(id),
  is_self         INTEGER NOT NULL DEFAULT 0,
  display_name    TEXT NOT NULL,
  phone           TEXT,
  municipality    TEXT NOT NULL,
  zone            TEXT,
  consent_at      TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  confirmed_at    TEXT
);
-- Exact location, only when the caregiver chose to share it (browser geolocation). NULL = municipality + zone only.
ALTER TABLE patients ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS location_accuracy_m DOUBLE PRECISION;
CREATE UNIQUE INDEX IF NOT EXISTS one_self_patient ON patients(caregiver_id) WHERE is_self = 1;
CREATE INDEX IF NOT EXISTS patients_place ON patients(municipality, zone);

CREATE TABLE IF NOT EXISTS patient_needs (
  patient_id    INTEGER NOT NULL REFERENCES patients(id),
  kind          TEXT NOT NULL CHECK (kind IN ('oxygen','cpap','ventilator','dialysis','insulin','other')),
  battery_hours DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS intakes (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caregiver_id INTEGER NOT NULL REFERENCES users(id),
  patient_id   INTEGER REFERENCES patients(id),
  transcript   TEXT NOT NULL,
  ai_json      TEXT,
  status       TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','confirmed','rejected'))
);

CREATE TABLE IF NOT EXISTS zones (
  municipality TEXT NOT NULL,
  zone         TEXT NOT NULL,
  PRIMARY KEY (municipality, zone)
);

-- Every LUMA reading, failures included. ok = 1 only when the payload parsed.
CREATE TABLE IF NOT EXISTS luma_readings (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fetched_at     TEXT NOT NULL DEFAULT iso(now()),
  source         TEXT NOT NULL DEFAULT 'live' CHECK (source IN ('live','replay')),
  endpoint       TEXT NOT NULL CHECK (endpoint IN ('regions','towns')),
  request_body   TEXT,
  http_status    INTEGER NOT NULL, -- 0 = no response (timeout, network)
  ok             INTEGER NOT NULL,
  error          TEXT,
  payload        TEXT,
  luma_timestamp TEXT
);

CREATE TABLE IF NOT EXISTS outage_events (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id        INTEGER NOT NULL REFERENCES patients(id),
  opened_reading_id INTEGER NOT NULL REFERENCES luma_readings(id),
  closed_reading_id INTEGER REFERENCES luma_readings(id),
  status            TEXT NOT NULL DEFAULT 'possible' CHECK (status IN ('possible','confirmed','restored','false_alarm')),
  mode              TEXT NOT NULL DEFAULT 'live' CHECK (mode IN ('live','replay')), -- replay events never touch live ones
  opened_at         TEXT NOT NULL DEFAULT iso(now()),
  closed_at         TEXT,
  claimed_by_org_id INTEGER REFERENCES organizations(id),
  claimed_by        INTEGER REFERENCES users(id),
  claimed_at        TEXT
);
-- One open incident per patient per mode.
CREATE UNIQUE INDEX IF NOT EXISTS one_open_event ON outage_events(patient_id, mode) WHERE status IN ('possible','confirmed');

CREATE TABLE IF NOT EXISTS checkins (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id     INTEGER NOT NULL REFERENCES outage_events(id),
  sent_at      TEXT NOT NULL DEFAULT iso(now()),
  message      TEXT NOT NULL,
  reply_text   TEXT,
  reply_at     TEXT,
  ai_parsed    TEXT,
  confirmed_by INTEGER REFERENCES users(id),
  confirmed_at TEXT
);

CREATE TABLE IF NOT EXISTS briefings (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      INTEGER NOT NULL REFERENCES outage_events(id),
  draft_text    TEXT NOT NULL,
  approved_text TEXT,
  approved_by   INTEGER REFERENCES users(id),
  approved_at   TEXT
);

CREATE TABLE IF NOT EXISTS call_outcomes (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id       INTEGER NOT NULL REFERENCES outage_events(id),
  coordinator_id INTEGER NOT NULL REFERENCES users(id),
  reached        INTEGER NOT NULL,
  outcome        TEXT NOT NULL,
  next_action    TEXT,
  created_at     TEXT NOT NULL DEFAULT iso(now())
);

-- WhatsApp chat of a case (server/whatsapp.ts). 'out' rows are written before sending, so a send is never repeated;
-- error holds a failed send or delivery. wa_id is Twilio's MessageSid: it dedupes webhook retries and maps quoted replies.
CREATE TABLE IF NOT EXISTS messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id   INTEGER NOT NULL REFERENCES outage_events(id),
  dir        TEXT NOT NULL CHECK (dir IN ('out','in')),
  phone      TEXT NOT NULL, -- digits with country code
  body       TEXT NOT NULL,
  wa_id      TEXT UNIQUE,
  error      TEXT,
  sent_by    INTEGER REFERENCES users(id), -- NULL = automatic (check-in, receipt)
  created_at TEXT NOT NULL DEFAULT iso(now())
);
CREATE INDEX IF NOT EXISTS messages_phone ON messages(phone, dir);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO settings (key, value) VALUES ('mode', 'live'), ('replay_cursor', '0') ON CONFLICT DO NOTHING;

-- Supabase also publishes every table through its Data API (anon key). RLS on with no policies shuts that door;
-- the server connects as the owning role, which RLS does not restrict. The browser only ever talks to /api.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = current_schema() LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;
